name: MDAudio
version: ${project.version}
main: us.magicaldreams.mdaudio.Main
api-version: 1.13
authors: [chums122]
description: MagicalDreams Custom Audio Server
website: https://magicaldreams.us/
commands:
  test:
    description: test
    usage: /test
  audio:
    description: Link stuffs
    usage: /audio